version: '3.7'
services:
  shaark:
    image: shaark:${SHAARK_IMAGE_TAG:-latest}
    build: .
    restart: unless-stopped
    ports:
      - target: 80
        published: ${SHAARK_PORT:-80}
        protocol: tcp
        mode: host
    depends_on:
      - mariadb
      - redis
    entrypoint: ['./app/wait-for-it.sh', 'mariadb:3306', '-t', '30', '--', './app/entrypoint-shaark.sh'] 
    environment:
      APP_MIGRATE_DB: ${SHAARK_MIGRATE_DB:-false}
      APP_ENV: "production"
      APP_DEBUG: ${SHAARK_DEBUG:-false}
      APP_URL: ${SHAARK_URL:-http://localhost}
      DB_PASSWORD: ${SHAARK_DATABASE_PASSWORD:-secret}
      DB_USER: ${SHAARK_DATABASE_USER:-homestead}
      DB_DATABASE: ${SHAARK_DATABASE_NAME:-homestead}
    volumes:
      - archives:/app/storage/app/archives
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  mariadb:
    image: mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SHAARK_MYSQL_ROOT_PASSWORD:-rootpassword9867ow3q459087w980}
      MYSQL_PASSWORD: ${SHAARK_DATABASE_PASSWORD:-secret}
      MYSQL_USER: ${SHAARK_DATABASE_USER:-homestead}
      MYSQL_DATABASE: ${SHAARK_DATABASE_NAME:-homestead}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redis:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

volumes:
  redis: {}
  mariadb: {}
  archives: {}
